baseURL = 'https://allbctl.aallbrig.com/'
languageCode = 'en-us'
title = 'allbctl Documentation'
theme = 'hugo-book'

[params]
  BookTheme = 'auto'
  BookToC = true
  BookRepo = 'https://github.com/aallbrig/allbctl'
  BookEditPath = 'edit/main/hugo/site/content'
  BookDateFormat = 'January 2, 2006'
  BookSearch = true
  BookComments = false

[menu]
  [[menu.before]]
    identifier = 'github'
    name = 'GitHub'
    url = 'https://github.com/aallbrig/allbctl'
    weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
